dist: trusty
sudo: required

language: scala

git:
  depth: 3
  quiet: true

env:
  - JAVA_OPTS="-DSKIP_FLAKY=true -Dsbt.log.noformat=true"

# These directories are cached to S3 at the end of the build
cache:
  directories:
   - $HOME/.ivy2/cache
   - $HOME/.ivy2/local/com.twitter
   - $HOME/.sbt

before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache  -name "ivydata-*.properties" -delete
  - find $HOME/.sbt         -name "*.lock"               -delete

scala:
  - 2.12.8

jdk:
  - oraclejdk8

before_script:
  - unset SBT_OPTS # default $SBT_OPTS is irrelevant to sbt launcher

script:
  - travis_retry ./sbt ++$TRAVIS_SCALA_VERSION clean coverage test coverageReport

after_success:
  - ./sbt ++$TRAVIS_SCALA_VERSION coverageAggregate
  - bash <(curl -s https://codecov.io/bash)
